//
//  RudderUITests.swift
//  RudderUITests
//
//  Created by Satheesh Kannan on 07/05/26.
//

import XCTest

/**
 * RudderUITests is the default UI test class generated by Xcode.
 *
 * It provides a standard template for writing UI tests, including setup/teardown
 * methods and basic performance testing for application launch. It serves as a
 * general container for tests that verify the broad UI behavior of the application.
 */
final class RudderUITests: XCTestCase {

    override func setUpWithError() throws {
        // Put setup code here. This method is called before the invocation of each test method in the class.

        // In UI tests it is usually best to stop immediately when a failure occurs.
        continueAfterFailure = false

        // In UI tests it’s important to set the initial state - such as interface orientation - required for your tests before they run. The setUp method is a good place to do this.
    }

    override func tearDownWithError() throws {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
    }

    @MainActor
    func testExample() throws {
        // UI tests must launch the application that they test.
        let app = XCUIApplication()
        app.launch()

        // Use XCTAssert and related functions to verify your tests produce the correct results.
        // XCUIAutomation Documentation
        // https://developer.apple.com/documentation/xcuiautomation
    }

    @MainActor
    func testLaunchPerformance() throws {
        // This measures how long it takes to launch your application.
        measure(metrics: [XCTApplicationLaunchMetric()]) {
            XCUIApplication().launch()
        }
    }
}

// MARK: - MCP Gateway

/// Run this test, then open Claude Code in this repo directory.
/// Claude discovers the 20 rudder.* tools via .mcp.json and drives the SDK
/// based on natural-language prompts — no scripted test needed.
final class MCPGatewayTest: ScenarioTestCase {

    func testMCPGateway() throws {
        guard ProcessInfo.processInfo.environment["MCP_GATEWAY"] == "1" else {
            throw XCTSkip("MCP gateway skipped. Set env var MCP_GATEWAY=1 in the scheme to enable.")
        }
        rudderScenario(initAnalytics: false) { [unowned self] _ in
            guard let interpreter = self.interpreter else { return }
            let mcp = MCPServer(interpreter: interpreter)
            mcp.start(port: 7777)
            print("[MCPGateway] Ready — connect Claude Code at http://127.0.0.1:7777")
            let timeout = ProcessInfo.processInfo.environment["MCP_GATEWAY_TIMEOUT"]
                .flatMap(TimeInterval.init) ?? 600
            Thread.sleep(forTimeInterval: timeout)
            mcp.stop()
        }
    }
}
