# Disable unwanted rules
disabled_rules:
    - redundant_string_enum_value
    - file_length
    - trailing_whitespace

# Enable additional rules
opt_in_rules:
    - force_unwrapping
    - missing_docs
    - explicit_init
    - redundant_nil_coalescing
    - fatal_error_message
    - empty_count
    - no_empty_block
    - return_arrow_whitespace
    - multiline_parameters_brackets
    - multiline_arguments
    - attributes
    - function_default_parameter_at_end
    - no_magic_numbers

# File and Directory Exclusions
excluded:
    - '**/Analytics/AnalyticsTests/**'
    - '**/AnalyticsApp/**'

# Discourages using `as!`
force_cast:
    active: true
    severity: warning
  
# Discourages using `try!`
force_try:
    active: true
    severity: warning

# Avoids tuples with too many elements
large_tuple:
    warning: 3
    error: 6
  
type_name:
    excluded: ["T"]
    
# Complexity Rules:
cyclomatic_complexity:
    ignores_case_statements: true
  
type_body_length:
    warning: 600
    
function_body_length:
    warning: 125

# Number of parameters allowed in the function
function_parameter_count:
    warning: 8
    error: 12

# Formatting
line_length:
    warning: 250
    error: 300
    ignores_urls: true
    ignores_comments: true
    ignores_function_declarations: true

nesting:
    type_level: 2
