# Disable unwanted rules
disabled_rules:
    - redundant_string_enum_value
    - file_length
    - trailing_whitespace

# Enable additional rules
opt_in_rules:
    - force_unwrapping  # Discourages using `!`
    - missing_docs  # Requires documentation for public APIs
    - explicit_init  # Requires explicit `.init()` for clarity
    - redundant_nil_coalescing  # Detects unnecessary nil coalescing (`?? nil`)
    - fatal_error_message  # Detects empty fatal errors without message
    - empty_count # Detects irrelavant empty checks
    - identifier_name # Naming conventions rule for variables, Default
    - nesting # Related to nested types and methods, Default
    - no_empty_block # Discourages having empty blocks

# File and Directory Exclusions
excluded:
    - '**/Analytics/AnalyticsTests/**'
    - '**/AnalyticsApp/**'

# Discourages using `as!`
force_cast:
    active: true
    severity: warning
  
# Discourages using `try!`
force_try:
    active: true
    severity: warning

# Avoids tuples with too many elements
large_tuple:
    warning: 3
    error: 6

line_length:
    warning: 250
    error: 300
    ignores_comments: true
    ignores_function_declarations: true
  
type_name:
    excluded: ["T"]
    
# Complexity Rules:
cyclomatic_complexity:
    ignores_case_statements: true
  
type_body_length:
    warning: 600
    
function_body_length:
    warning: 60

# Number of parameters allowed in the function
function_parameter_count:
    warning: 8
    error: 12
