sonar.log.level=INFO
sonar.verbose=false
sonar.qualitygate.wait=false

# Project details
sonar.projectKey=rudderlabs_rudder-sdk-swift
sonar.organization=rudderlabs
sonar.projectName=RudderStack Swift SDK

# Meta-data for the project
sonar.links.scm=https://github.com/rudderlabs/rudder-sdk-swift
sonar.links.issue=https://github.com/rudderlabs/rudder-sdk-swift/issues

# Path to sources
sonar.sources=Sources/RudderStackAnalytics

# Source encoding
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
sonar.cpd.exclusions=Examples/**/*
