name: PR Validation

on:
    pull_request:
      branches: [ "main", "develop", "feat/*", "refactor/*", "release/*", "ci/*", "fix/*" ]
      types: [ "opened", "reopened", "synchronize", "edited" ]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref }}
    cancel-in-progress: true
    
jobs:
    swiftlint-check:
      name: SwiftLint Check
      runs-on: macos-latest
      steps:
        - name: Harden the runner (Audit all outbound calls)
          uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
          with:
            egress-policy: audit

        - name: Checkout code
          uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

        - name: Install SwiftLint
          run: brew install swiftlint

        - name: Run SwiftLint
          run: swiftlint lint --reporter github-actions-logging

    test-check:
      name: Unit Tests
      runs-on: macos-latest
      steps:
        - name: Harden the runner (Audit all outbound calls)
          uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
          with:
            egress-policy: audit

        - name: Checkout code
          uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

        - name: Build for testing
          run: swift build --build-tests

        - name: Run tests
          run: swift test --skip-build --no-parallel

    build-check:
      name: SPM Build Verification
      runs-on: macos-latest
      needs: [ swiftlint-check, test-check ]
      steps:
        - name: Harden the runner (Audit all outbound calls)
          uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
          with:
            egress-policy: audit

        - name: Checkout code
          uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

        - name: Build Swift package
          run: swift build

